#!/usr/bin/python
import sys
sys.path.insert(0,'/usr/lib/entropy/libraries')
sys.path.insert(0,'/usr/lib/entropy/client')
sys.path.insert(0,'../libraries')
sys.path.insert(0,'../client')
# disable pid management
sys.argv.append("--no-pid-handling")
from entropy import SocketHostInterface, EquoInterface
srv = SocketHostInterface(EquoInterface)
srv.go()

