PREFIX ?= /usr
BINDIR ?= $(PREFIX)/bin
LIBDIR ?= $(PREFIX)/lib
DESTDIR ?= 

all:


install:
	install -d $(DESTDIR)/$(LIBDIR)/entropy/lib/kswitch
	install -m 644 *.py $(DESTDIR)/$(LIBDIR)/entropy/lib/kswitch/

clean:
