#!/usr/bin/python
'''
    # DESCRIPTION:
    # this application gets a .tbz2 file as input and creates the dependency binary metafile
    # that another application could handle using portage and binpackages extensions directly

    Copyright (C) 2007 Fabio Erculiani

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
'''

# Never do "import portage" here, please use entropyTools binding

import os
import sys
import string

sys.path.append('../libraries')
import entropyTools
import reagentTools
from entropyConstants import *

# CONSTANTS
APPNAME = "reagent"
APPVERSION = "1.0"
def print_help():
    print "* info  * : Sabayon Linux "+APPNAME+" (C - 2007)"
    print
    print "* usage * : "+APPNAME+" <tool, not mandatory> <valid path or .tbz2 file>"
    print "* opts  * : --help\t\tthis output"
    print "* opts  * : --version\t\tprint version"
    print
    print "* info  * : tools available: "
    print "* info  * : \tdigest\t to create digest of a specified directory"
    print

options = sys.argv[1:]

# print version
if (string.join(options).find("--version") != -1) or (string.join(options).find(" -V") != -1):
    entropyTools.print_generic(APPNAME+": "+APPVERSION)
    sys.exit(0)

# print help
if len(options) < 1 or string.join(options).find("--help") != -1 or string.join(options).find(" -h") != -1:
    print_help()
    if len(options) < 1:
	entropyTools.print_error("not enough parameters")
    sys.exit(1)

if (not entropyTools.isRoot()):
    print_error("you must be root in order to run "+APPNAME)

# digest tool (creates a digest on the specified directory)
if (options[0].find("digest") != -1):
    reagentTools.createDigest(options[1])
    sys.exit(0)
# add other options here
# ...
# ...
# tbz2 tool
if (not options[0].endswith(".tbz2")):
    entropyTools.print_error("no .tbz2 file specified")
    sys.exit(3)

validFile = False
for i in options:
    if os.path.isfile(i) and i.endswith(".tbz2"):
	validFile = True
	tbz2File = i
	break

if (not validFile):
    entropyTools.print_error("no valid .tbz2 file specified")
    sys.exit(4)


entropyTools.print_info("extracting data and calculating info for: "+tbz2File.split("/")[len(tbz2File.split("/"))-1]+" please wait...")
# fill all the info
etpData = reagentTools.extractPkgData(tbz2File)

# look where I can store the file and return its path
etpOutput, etpOutfilePath = reagentTools.allocateFile(etpData)

if etpOutfilePath is not None:
    entropyTools.print_info("writing: "+etpOutfilePath)
    f = open(etpOutfilePath,"w")
    f.writelines(etpOutput)
    f.flush()
    f.close()
    # digesting directory
    reagentTools.createDigest(etpOutfilePath)
else:
    entropyTools.print_info("not generating a new .etp file, it's not needed")

# clean garbage
os.system("rm -rf "+etpConst['packagestmpdir']+"/"+etpData['name']+"-"+etpData['version'])