#!/bin/sh

kernels="2.6.31-sabayon 2.6.32-sabayon 2.6.33-sabayon 2.6.34-sabayon"
running_kernel="2.6.34-sabayon"
packages="app-emulation/virtualbox-guest-additions app-emulation/virtualbox-modules x11-drivers/xf86-video-virtualbox"

export ETP_REPO="sabayonlinux.org"

# build for latest kernel
KERNEL_DIR="/usr/src/linux-${running_kernel}" emerge xf86-input-virtualbox $packages virtualbox-bin
echo -5 | etc-update
reagent update

for kernel in $kernels; do
        if [ "${kernel}" = "${running_kernel}" ]; then
                continue
        fi
        rm -rf /usr/portage/packages/*
        KERNEL_DIR="/usr/src/linux-${kernel}" emerge -B ${packages} || ( echo "ouch unable to build" && exit 1 )
        built_pkgs=$(find /usr/portage/packages -name "*.tbz2" | xargs echo)
        [[ -z "${built_pkgs}" ]] && echo "ouch no kernel pkgs" && exit 2
        reagent inject ${built_pkgs} || ( echo "ouch unable to inject" && exit 3 )
        echo
        reagent query tags ${kernel} -qv | sort
        echo
done

echo "Now you should remove old packages:"
echo ETP_REPO=sabayonlinux.org reagent repo remove `reagent query search virtualbox -qv | grep MY_OLD_VER | xargs echo`
echo
