=head1 NAME

B<activator> - Official Sabayon Linux Server-Side Repositories Management tool.

=head1 SYNOPSIS

B<activator> [action] [basic_options] [options] [atom | package_file | @set] ...

B<activator> [action] [basic_options] [options] ...

B<activator> --help

B<activator> --version

=head1 DESCRIPTION

 work in progress

=head1 BASIC_OPTIONS

 work in progress

=head1 OPTIONS

 work in progress

=head1 ENVIRONMENT

B<ETP_REPO>=valid repository id: on-the-fly switch default Entropy repository.

B<ETP_EXPIRATION_DAYS>=valid number: on-the-fly removed packages expiration days
setting.

=head1 BUGS

Please report bugs to http://bugs.sabayonlinux.org.

=head1 EXAMPLES

 work in progress

=head1 EXIT STATUS

B<activator> returns a zero exit status if the called command succeeded. Non zero
is returned in case of failure.

=head1 AUTHOR

Fabio Erculiani <lxnay@sabayon.org>

=head1 SEE ALSO

reagent(1), equo(1)